 databases:
     - name: agro
       databaseName: agro_v6zs
       user: agro_v6zs_user

Services:
     - type: web
       name: agrochem19
       env: python
       buildCommand: "pip install requirements.txt"
       startCommand: "gunicorn agrochem19.wsgi:application"
       envVars:
         - key: DATABASE_URL
           fromDatabase:
             name: agro
             property: connectionString
         - key: SECRET_KEY
           generateValue: true
         - key: WEB_CONCURRENCY
           value: 4