# Generated by Django 4.2.6 on 2023-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_img', models.CharField(max_length=200)),
                ('news_text', models.CharField(max_length=200)),
                ('news_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
