# Generated by Django 4.2.6 on 2023-10-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='static/AgroChemical/img/')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': ('Слайды',),
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': ('Новость',), 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='static/AgroChemical/img/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(),
        ),
    ]
