# Generated by Django 4.2.6 on 2023-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slides_alter_news_options_alter_news_news_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='main/static/AgroChemical/image/'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='img',
            field=models.ImageField(upload_to='main/static/AgroChemical/image/'),
        ),
    ]
