# Generated by Django 4.2.6 on 2023-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_news_img_alter_slides_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='static/AgroChemical/image/'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='img',
            field=models.ImageField(upload_to='static/AgroChemical/image/'),
        ),
    ]
