# Generated by Django 4.2.6 on 2023-10-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_page_pageelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.TextField()),
                ('rows', models.TextField()),
                ('page_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pageelement')),
            ],
        ),
        migrations.CreateModel(
            name='ListElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('page_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pageelement')),
            ],
        ),
    ]
