# Generated by Django 4.2.6 on 2023-10-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tableelement_listelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageelement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='tableelement',
            name='page_element',
        ),
        migrations.DeleteModel(
            name='ListElement',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageElement',
        ),
        migrations.DeleteModel(
            name='TableElement',
        ),
    ]
