# Generated by Django 4.2.6 on 2023-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_news_news_img_alter_slides_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtCode', models.IntegerField(verbose_name=50)),
                ('districtName', models.CharField(verbose_name=200)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='img',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
