# Generated by Django 4.2.6 on 2023-11-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_district_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
