# Generated by Django 4.2.6 on 2023-11-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_farm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farm',
        ),
    ]
